server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myvhr?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: "wy383614"

    # HTTP ENCODING
    http:
      multipart:
        max-file-size: 2MB
        max-request-size: 10MB
      encoding:
        enabled: true
        charset: UTF-8
        force: true
  jackson:
    date-format: yyyy-MM-dd #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss #使用时间戳，使用数值timestamp表示日期
# MyBatis
mybatis:
  type-aliases-package: com.why.myvhr.beans
  mapper-locations: classpath:/mappers/*.xml
pagehelper:
  helperDialect: mysql # 根据数据库配置
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.why.myvhr.mapper: DEBUG
